version: "3"

services:
  trade-bot:
    build: .
    container_name: binance-trade-bot
    environment:
      TZ: Australia/Melbourne
      CONFIG_DIR: /config
      CONFIG_NAME: user.cfg
    volumes:
    - ./config:/config
    - ./log:/log
    - ./state:/state