version: "3"

services:
  trade-bot:
    build: .
    container_name: binance-trade-bot
    environment:
      TZ: Australia/Melbourne
    volumes:
    - ./config:/config
    - ./log:/log
    - ./state:/state